site_name: 风雪的数字花园
site_url: https://altair-albert.github.io/
site_description: '机器人, 算法, Rust, C/C++, Python, Java'
site_author: "Albert Lv <altair.albert@gmail.com>"

copyright: '本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a>进行许可。'

theme:
  name: material
  icon:
    logo: material/flask-outline
  language: zh
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - toc.follow

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      baselevel: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - tags:
      tags_file: tags.md
  - obsidian-bridge
  - include_dir_to_nav
  - callouts
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      js_files:
          - js/mathjax.js
      css_files:
          - css/fix.css

nav:
  - 基础工具: '基础工具/'
  - 机器人: '机器人/'
  - 机器视觉: '机器视觉/'
  - 杂项: '杂项/'
  - 归类: tags.md
  - 关于: '关于/'

extra:
  analytics:
    provider: google
    property: G-LPSL3YGLRT

extra_css:
  - css/fix.css
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    #- https://unpkg.com/mermaid/dist/mermaid.min.js
